spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springdata?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent_output: true
  thymeleaf:
    cache: false

logging:
  level:
    org:
      springframework:
        security: info
