spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springdata?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    serialization:
      indent_output: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

logging:
  level:
    org:
      springframework:
        security: info
